### ISSUE TITLE
Updating Remote DB multiple progress windows.

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/OpenKJ#123]
When testing out pushing songs to my remote database, I was moving the OpenKJ progress bar window out of the way so I could do something else and I noticed there was another below it... and then moved that one and noticed there was another below that... 3 in total. Not sure how that happened but according to my debugging it seems that only one API request is going through to the server at a time... so it's not like I'm getting 3 of the same songs. Any ideas?
![image](https://user-images.githubusercontent.com/526491/49739908-a1ff8800-fc58-11e8-842a-3fb5759917ed.png)

**Comment by generalredneck** [comment]
Interesting Side note... when my Song database got up to 95%, one of the windows disappeared, but looking at the api debug output I made for myself, it looks like all the songs have went through cause the last page in the api wasn't 1000, but only ~800... (I have approx 70,000 files I'm processing) Maybe we have some rounding errors mixed with some race conditions? Will debug some more later and see what I can come up with.

**Comment by coyote1357** [comment]
That's extremely odd.  I'll do some testing and see if I can duplicate it.

What version are you using?

**Comment by generalredneck** [comment]
OpenKJ

Version: 1.4.5 stable
Built: Nov 28 2018 04:47:09
License: GPL v3+

**Comment by coyote1357** [comment]
I was able to trigger the same issue.  I'm looking into it.

**Comment by coyote1357** [comment]
Fixed in 1.5.17 unstable.  Will roll to release in the next week or so.

You were correct that it was getting updated and just reporting percentages wrong.  The progress dialog was off by one chunk (the db is broken up into smaller chunks to avoid timeouts on the server side).  Mixup between 0 based and 1 based counting.

The dialog popping up multiple times was due to the progress dialog object that is dynamically created not getting deleted properly.  Each time you ran the db update, it was creating a new one, and all of them were still connected to the progress events so they were magically reappearing after being closed on previous updates.

**Comment by generalredneck** [comment]
Got it... this would also explain why when I hit the "close" button on the dialog the sync process that the dialogs pop back up even after closing the application.

**Comment by coyote1357** [comment]
You should see 1.5.18 available in the ppa now.  Sorry for the lag, launchpad doesn't support github hooks (that I've been able to figure out, anyway), so it just gets built daily if there are any changes to build.  I usually manually trigger a build for bugfixes, but forgot about it this time around.

**Comment by altere987** [comment]
Linux Mint 18.3 Cinnamon 64-bit
OpenKJ 1.5.20

Below are 2 screenshots of what I'm getting when selecting my folder and clicking Update, the second Database Update window comes up. No progress bar, can't click on anything. Was stuck on that for about 5-10 minutes, I was about to hit the X to exit because I wasn't sure it was doing anything. Finally after the long wait, the progress bar came up but the whole theme changed white. After the update was complete, before closing I clicked on Tools->Settings and the only option was Audio, (I believe you mentioned part of this with the theme might be Qt, would that still be the case with missing options?)the rest was missing.

![screenshot from 2018-12-21 16-18-39](https://user-images.githubusercontent.com/35095431/50365951-7c1d9180-053c-11e9-8c3a-b3343c6e501c.png)

![screenshot from 2018-12-21 16-24-31](https://user-images.githubusercontent.com/35095431/50366108-6c527d00-053d-11e9-9eb6-30f7a1fd14b0.png)

**Comment by coyote1357** [comment]
That is bizarre, it's working flawlessly on Fedora.

I'll have to throw together a test VM and figure out what's going on.

**Comment by generalredneck** [comment]
Getting back on track, altere987's messages above are supposed to be on a different thread (as stated in his edit).

Given that, testing the original issue produced the following results...

I initially pressed the Update Remote DB button twice. This produced 2 progress bars... Closing them doesn't cancel api sync like I expected but this is a separate issue and I couldn't remove 2 progress bars showing. After they both hit 100%, one of them disappeared and the "Successful" dialog showed up. Then the second one started over at 0% and started the update over again... So here is what I expected to happen and you can work out what is the actual behavior from there... though I think the original issue of several dialogs showing up upon a single click of the Update Remote DB button is technically fixed.

* Pressing the Update Remote DB button should produce the yes/no dialog to continue.
* After Choosing "Yes" then the progress bar should appear
* Pressing "close" on the progress bar should kill the syncing task after the api returns a success or fail.
* While the progress bar is displayed the "update Remote DB" button should be disabled so it can't be hit again causing the weirdness of multiple progress bar dialogs and the train of clearing and resyncing that happens thereof.

**Comment by coyote1357** [comment]
Just pushed a fix for the behaviours additionally brought up by @generalredneck.  Will be in the next unstable build.
