### ISSUE TITLE
Feature Request: Introduction of tags for song management

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#143]
I've thought about this one for a while, and I think the introduction of tags into OKJ would be great .... they are simple, but ultra effective, take up literally no space, and YOU are in full control of what YOU want to tag things with. If any of you are MacOS or Linux users, then you already know what I'm talking about. 

So lets say you wanted to have a theme night for 1960s or perhaps a country based night, finding all your relevant songs would not be easy, unless you are a host that already has an amazing and pristine organised library ;)

An example of things you a host may want to search for:

*decade* (great for theme nights, but also people will ask "what do you have for 80's rock?")
*genre* (i.e AC/DC would fall under Rock, Hard Rock, & Classic Rock) 
*Duet* (people CONSTANTLY ask what we have for duets) 
*Language* (also, get asked what we have for Spanish or French music for example) 
*explicit* (mark a song as having explicit lyrics)

To create tags, it takes seconds, just type the tags you wish to create in the system. When you want to start applying then, you could utilise the existing song search engine to start with, however it would probably be better to create a corresponding function to then be able to apply those tags in bulk across your song library, and allow you to specify search filters to identify tracks you wish to apply those tags to. 

For example: 

Step 1: "Please select the tags you wish to apply" 
So you select "90s, Rock, English, Clean" 

Step 2: "Please select the tracks you wish to apply the tags to" 
In this step you should be able to filter using multiple criteria that you specify. 

i.e. Name contains "Nirvana" and 'filename prefix' + ' begins with' "SF, SFMW, SFG" .... this would result only in tracks starting with Sunfly based prefixes and has Nirvana in them. 

Step 3 - Select the tracks within the results, either Select All, or just specific ones. 

Step 4 - Apply. 

Step 5 - Rinse and Repeat. 

The above is a crude example, but you get the idea, the tags would also be searchable to find songs too. So if you wanted to find all your SoundChoice Country songs from the 90's, search with the tags: 

90s, Country, SoundChoice. 

It's not just be for song management either, tags could be incorporated into the OKJ songbook too. You could offer the ability for users to narrow searches down based on existing tags, or you could choose to display songs tags in the songbook, you could also make those tags selectable. 

For example, the may search for 'Nirvana' and those songs have tags like 90s, Grunge, Rock etc .... so they could then tap 'Grunge' and now all songs with the 'Grunge' tag is displayed and so on and so on.....

There is a tonne of other things you could utilise tags for and with, so I hope it will be given some thought.

**Comment by jpoconnor61** [comment]
I have implemented this in the filename text for relevant song files, probably more for my own use rather than pushing it to users, who might otherwise figure it out anyway.

As such, I think they work ok in the app or webpage search. except you can't block or filter by these keywords.

I use them for Categorization as well as flagging of features, so one of my entries might read -

 [Chartbuster] - Peabo Bryson & Regina Belle - A Whole New World (Aladdin) [Duet] [Disney]

Using the default OKJ library import mask, this puts [Chartbuster] in as the SongID and the trailing tags are included as part of the Song Title.

Other tags I use - [WVocals] [NSFW] [Parody] [Funny] [XMAS] [NonEnglish] [Musical] [Gospel] [KIDS].

Enough exposure to this might lead to singers realizing they can use them in their keyword searches.

![sample](https://user-images.githubusercontent.com/46508999/52826026-e270fb80-310a-11e9-8b18-48140241b35c.jpg)

External to OKJ, I can use some of these tags to filter lists in preparation for updating the online list or even copying files to a disk for loading into the OKJ library.

If it were to be incorporated into the App or Webpage search, a list of radio buttons or slide switches for Tag criteria could appear on the same page as the Search box.

JOC

**Comment by backstagekaraoke** [comment]
@jpoconnor61 

Hey mate, yeah there is multiple ways hosts can 'organise' their libraries .... I can see pro's in your method also. 

Using tags removes the dependency from the files themselves, meaning you can leave the files named however you wish, and tag as you wish. Your naming convention will still work, but only for a karaoke program that supports specifying your own naming masks (like OpenKJ) ... I lot of karaoke software, has either specific naming masks that cannot be changed, or can only change the delimiters, not the masking itself. Also tags won't be displayed in the filenames, so that allows you to keep the names very clean. i.e. '[Chartbuster] - Peabo Bryson & Regina Belle - A Whole New World (Aladdin) [Duet] [Disney]' is quiet a long song name entry haha

There is no reason, that you couldn't use both your naming convention and tags together though. Depending on if and how tags are implemented, your library would actually be very easy to do, as you essentially already have 'tags' of stuff in the names ....

e.g. you could just do a search for any file with [Duet] in the name and tag it with 'Duet' etc 

Tags may not give specifically you much benefit as you already have a very well organised library .... it will however help hosts a lot who dont have an impeccable library, or want a simpler naming convention for their files.

**Comment by backstagekaraoke** [comment]
moved to Discussions > Ideas area
