### ISSUE TITLE
Bug: OpenKJ - Position Column disappears after restart or crash

### ISSUE THREAD

**Issue by backstagekaraoke** [OpenKJ/OpenKJ#161]
OpenKJ 1.5.33
Windows 10 64bit

Issue
The position column next to the singers name, which shows their next song, disappears completely after a program restart or crash.

Steps to reproduce

1. Open OKJ
2. Add singers
3. Close OKJ and go back in

**Comment by backstagekaraoke** [comment]
here is a video 

[IMG_9133.mp4.zip](https://github.com/OpenKJ/OpenKJ/files/2973820/IMG_9133.mp4.zip)

**Comment by coyote1357** [comment]
It actually wasn't supposed to be showing their next song at all, that column was left over from when the layout used to be different and the rotation list was much wider to accommodate it.  So it's a bug that it's showing it at all, not the other way around.  Someone else has already requested that it be optionally be added back, so that's on the list.

**Comment by coyote1357** [comment]
1.5.42 is building now, it adds an option under settings on the rotation tab to display the next song for the singers in the rotation list.  It also auto-sizes the name column to the longest singer name in the rotation and gives whatever free space is left over to the next song when it is visible.

**Comment by backstagekaraoke** [comment]
@coyote1357 tested on Linux Mint with both kernel 4.15.47 and 5.0.9 and seems to be working fine. Great addition! :)
