### ISSUE TITLE
Improve performance of initial import to KaraokeDB

### ISSUE THREAD

**Issue by jose1711** [OpenKJ/OpenKJ#193]
This may be concern to large collections and/or slow media (network-backed). I have run a small benchmark on a collection of 2000 mp3+cdg pairs residing on a rotational drive (14 GB total), filenames are in format "Artist - Title", karaoke db is empty.

Populating the DB using OpenKJ took approx. 17 seconds. A custom-made python script did it under a second. Maybe there are some areas that could be improved and/or this script could be put into `contrib/` section for those needing it.
```
#!/usr/bin/env python
'''
ARTIST1 NAME - SONG NAME1.cdg
ARTIST1 NAME - SONG NAME1.mp3
ARTIST1 NAME - SONG NAME2.cdg
ARTIST1 NAME - SONG NAME2.mp3
ARTIST2 NAME - SONG NAME1.cdg
ARTIST2 NAME - SONG NAME1.mp3
'''
from glob import glob
import os.path
import ffmpeg
import sqlite3

conn = sqlite3.connect(os.path.expanduser('~/.local/share/OpenKJ/OpenKJ/openkj.sqlite'))
curr_path = os.path.abspath('.')

print('Getting mp3 files inside the current directory..')
mp3_files = glob('*.mp3')
count = len(mp3_files)
for ix, mp3_file in enumerate(mp3_files):
    basename = os.path.splitext(mp3_file)[0]
    # duration = int(float(ffmpeg.probe(mp3_file)['format']['duration'])) * 1000
    absolute_path = os.path.join(curr_path, basename + '.cdg')
    duration = int(os.path.getsize(absolute_path) / 96 / 75 * 1000)
    artist, track = basename.split(' - ', 1)
    search_string = basename + ' ' + artist + ' ' + track
    print('{ix}/{count} {basename} ({duration})'.format(**locals()))
    conn.execute('INSERT INTO main.dbSongs("songid","Artist","Title","DiscId","Duration","path","filename","searchstring") VALUES (NULL,"{artist}","{track}","","{duration}","{absolute_path}","{basename}","{search_string}")'.format(**locals()))

conn.commit()
```

**Comment by backstagekaraoke** [comment]
@coyote1357 - Any thoughts on this one mate?

**Comment by mikecrews** [comment]
I would like to add to this issue my observation that the initial indexing of a folder containing a large collection consisting of 175,000 files is getting slower and slower as it progresses. When it began, the count was rising at the rate of hundreds of files per second. Now it's at about file 145,000 and it is incrementing the counter at only 4-5 files per second. At this rate it will take longer to scan the last 20% than it did to scan the first 80%.

**Comment by dtromb** [comment]
Why was this closed?  This is a showstopper for me, I have to use something else...

**Comment by backstagekaraoke** [comment]
> Why was this closed? This is a showstopper for me, I have to use something else...

it was closed because you're the only one who seems to be having this issue, also when you logged it, you were using 1.6.7. Current stable is 2.0.3, so I recommend using that.

Also all attempts to try and reproduce this behaviour across multiple devices and platforms has failed, and import speeds are fine. My own library of around 63k tracks imports in less than 1 min.

Either its a local device issue, or your own expectations need to be adjusted in regards to what the import speed should be.

**Comment by dtromb** [comment]
Uh, I'm not the initial poster, I am a new user.   I just installed for the first time tonight from the current release on a reasonably fast fresh Ubuntu (32Gb RAM, i7-4770K CPU @ 3.50GHz) and the database import has been running for three hours with no signs of finishing.  It is slowing down as it nears completion.   Please listen to your users and investigate instead of dismissing them.

**Comment by ILightburn** [comment]
@dtromb  - A couple of questions...

Are you using filename based song naming or metadata?  For metadata (media tags), it has to unzip every single file to read the tags on the audio file.  This can be extremely slow and is heavily dependent on the speed of your storage and CPU. (assuming your files are zipped and not loose mp3/cdg pairs)

Is your library local or stored on a NAS or other network share?  Since pro KJs typically have all of their songs on a local drive, the db update process isn't at all optimized for network storage.

You have an abnormally large library, I typically don't test with libraries above 100k songs. Most professional KJs have less than 80k songs due to the cost involved in legally acquiring that many songs. It's possible that the size of the library is causing cache contention/cache miss problems or that there's an underlying memory leak somewhere in the db update code that doesn't become apparent until the library becomes enormous.

You probably want to also make sure that "skip zip file validation" and "lazy load durations" are both checked in the database tab in settings, as both require partial unzipping of the zip files during the db update. (assuming your files are zipped and not loose mp3/cdg pairs)

Also, selecting the individual source directories and just clicking update rather than using the update all button may speed things up a bit. Update all does additional checks for missing/moved files that can slow things down.  Though this shouldn't affect an initial import much, just later updates.

When the the original issue was opened, the defaults were set to validate every zip file during update (unzipping them to ensure that there were valid mp3 and cdg files present), which was the cause of most of the reports of slowness at the time. Assuming you haven't enabled zip file validation or turned off lazy load durations, your issue is a different problem entirely, as they were only testing with 2k songs and you can update 2k songs in current versions fast enough that drawing and displaying the progress dialogs on-screen takes longer than the actual db update, even when running on a Raspberry Pi 4 w/ a USB 2.0 external drive.

**Comment by planetarian** [comment]
I have my karaoke tracks on a second partition on the system drive, a SATA-connected samsung evo 2TB SSD.
They are not zipped; just raw mp3+cdg files.
The media information is truncated on many files, so i'm just using "Artist - Title" from the filenames to build the metadata.
I've noticed the same issue as the others -- The import operation starts off extremely fast, around 200-300 items per second, but quickly slows down, and as of around the 30,000 item mark (this counts both mp3 and cdg files, since there are no zip files in this setup, so it's actually 15,000 tracks), it drops to around 20 items per second, and drops further over time.
