### ISSUE TITLE
MP4 Support

### ISSUE THREAD

**Issue by nickburrett** [OpenKJ/OpenKJ#194]
I have installed gstreamer via Brew but I still cannot access MP4's in OpenKJ.

All files appear as Error?

![Screenshot 2019-12-29 12 59 57](https://user-images.githubusercontent.com/9543168/71557232-2dea7a80-2a3b-11ea-86e0-97f7eb739e3e.png)

![Screenshot 2019-12-29 13 00 45](https://user-images.githubusercontent.com/9543168/71557236-42c70e00-2a3b-11ea-908f-d50a8fb30904.png)

**Comment by backstagekaraoke** [comment]
@nickburrett 

What version of OpenKJ are you running? - I brought this issue to Issac's attention and we fixed it a while ago - I can't recall the exact version that the fix was implemented though.

FYI on Mac, I wouldn't be running any version past 1.5.99 at this point.

Also if you need to remove OpenKJ to change versions, use AppCleaner to remove it and make sure to remove all associated files.

**Comment by backstagekaraoke** [comment]
@nickburrett typo - I meant no version after 1.5.x

**Comment by backstagekaraoke** [comment]
MP4 and other video files are fully supported across all OS aversions of OpenKJ, make sure you are running 1.8+
