### ISSUE TITLE
OpenKJ Improvement StandaloneRequestServer API

### ISSUE THREAD

**Issue by 01i** [OpenKJ/OpenKJ#209]
Would it be possible to add the Song ID to the addSongs request sent to the Request Server API when clicking "Update Remote DB"?

**Comment by backstagekaraoke** [comment]
@01i - can you please confirm why the SongID would be of any benefit on the server side? As hosts and users don't see that data (nor do they need to) on the server side through the Songbook app. Hosts can already see the SongID column in the OpenKJ software.

**Comment by 01i** [comment]
I don't use songbird, I host my own request system based on the StandaloneRequestServer package which I'd like to improve on. 

It would be useful to me, because I wish to have more information available to the user in the song request system. I plan to attempt some form of integration with the LastFM API so that I can pull out tags and store them with my tracks.

I'd ideally also like the track length to be sent with the SongID, giving the user to chose a preferred version of the song (let's say they prefer Zoom to SBI for example), and to know if they are requesting a version that's 10mins long. 

Song ID is also useful because my "additional" data tables will not reset on each update.

**Comment by ILightburn** [comment]
Since both the songbook service and the standalone request server use the same API class, this isn't something I can easily change without changing the songbook service as well.

There are only a handful of people who use the standalone request server stuff since it requires knowledge of how to setup a LAMP stack, so improvements focused on it aren't very high in the priority list compared to features that have more mass demand from the user base.

That said, if you want to write your own updater based on the db in the program, OpenKJ's db is just a sqlite database file that can be accessed from pretty much any programming or scripting language with database support.  Alternatively you could just have a web form to upload the entire db file to your web server and access the db data directly from there.  The table name containing the karaoke song info is dbsongs and the artist, title, and songid are stored in the artist, title, and discid fields. (It's discid because the db schema was developed way back in the stone ages when the only way you could get karaoke songs was on CD+Gs lol)
