### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by AThomsen** [OpenKJ/OpenKJ#212]
OpenKJ uses a lot of ram (easily 500 MB) when playing CDG-files. This is because the current implementation initially parses the entire cdg file and creates 16-bit image files of each frame which is stored in memory.
I don't like the current approach with trying to compress the images using gz-algorithms. This just sacrifices CPU for RAM. Low-end hardware is probably limited on both.

I would like to suggest the following implementation:
* CDG-file is read to memory
* A forward-only reader is implemented, keeping only an image of the current frame in memory, adding to that image as the track advances.
* Seeking will require the reader to reset the image and build the image from the start position to the requested frame.

Advantages to this design
* Much lower memory use
* Instant CDG playback

Disadvantages
* Seeking will experience a small lag. I too much of a problem, every X frame could be cached as snapshots.

Are you interested in this approach or do you see any problems with it? If time allows it I would like to give it a go.

**Comment by coyote1357** [comment]
I'm not sure how well that would work with the GStreamer AppSrc implementation and seeking.  It may work perfectly, but the AppSrc stuff tends to kinda be voodoo to get working right, at least at my skill level.  I'm a Linux engineer who taught himself c++ to write OpenKJ, which is why the code is varying levels of ugly depending on how early on I wrote that particular bit, btw lol.

The compression in memory thing was kind of a hacky workaround just to get it working on low RAM ARM devices (like a pi w/ 4GB or below), but wound up getting expanded to other low RAM systems as a stop-gap until I could come up with a plan for reducing the footprint.

One thing that I've been exploring is the possibility of keeping the decoded frames as indexed RGB (the native cdg format, after a fashion) in memory, each pixel just being a single uchar pointing to a palette index, instead of the much larger memory footprint RGB16 format I'm currently storing them in.  Ideally figuring out how GStreamer indexed8 format frames are supposed to be structured in memory (the documentation is a little vague) and just storing them that way and handing them to it and letting it do the frame type conversion since it's probably hw accelerated, or alternatively doing the conversion to RGB16 at time of frame request.  It would still use more RAM than decode on demand, but should be vastly smaller,l enough to not be problematic even on something like a RPi 4 4GB.

**Comment by coyote1357** [comment]
btw, if you want to chat about ideas and such outside of github issues, there's an OpenKJ discord server https://discord.gg/Cs8KKH6

**Comment by AThomsen** [comment]
There's a PR now that implements 8-bit indexed images. This cuts memory usage in half compared to before.

I still think there are improvements to be made, so let's keep this issue open.

BTW, what is the method `CdgParser::md5HashByTime` planned to do?

**Comment by coyote1357** [comment]
It's part of a cdg fingerprinting concept I'm working on.  Planned usage in
OpenKJ is for tracking when a file gets renamed outside of OpenKJ and also
for a future service that can look up song metadata by fingerprint in an
online database I'm planning on building.

**Comment by coyote1357** [comment]
Didn't actually mean to close this.

**Comment by coyote1357** [comment]
I'm gonna take a stab at only saving the frames with actual changes in them and implementing a lookup table to know which frame image to grab.  Some quick testing shows that the vast majority of frames (approx 70% - 80% in the ones I looked at) don't actually contain changes.  Could further reduce memory usage by a massive amount.

**Comment by coyote1357** [comment]
Okay, I had forgotten that I was already only saving a frame per 40ms, so the savings aren't as huge as I initially thought, but it's still worth it.  About to push a change up that implements it after running through some torture testing.  One one cdg, it took total program memory usage from 569MB to 379MB, another from 493MB to 395MB, and on a stupid long one (23 minutes long), from 2GB to 810MB

**Comment by AThomsen** [comment]
This is great!

I'll try to create an on-demand reader as well so that memory usage will not relate to size of the cdg. Hopefully this weekend if I get the time :crossed_fingers:

**Comment by coyote1357** [comment]
Just spent some quality time with valgrind and Coverity and fixed a crapload of memory leaks.  Memory consumption looks to be lower over-all and it should prevent it from slowly growing over time like it was.  Changes are currently in master

**Comment by AThomsen** [comment]
I now have a POC if this working. It needs a bit of refactoring and stress testing, so stay tuned!

With this, CDG playing is now instant (the cdg-file is read to memory - that's it), memory use is low and fps is no longer capped at 24.

**Comment by coyote1357** [comment]
Nice!  Btw, if you edit the settings file and add "testingEnabled=true" to the general section, it'll enable a testing menu where you can run some stress tests.  It's undocumented, since it was originally only meant for me, but since you're working on the codebase too, it may be handy. :)

**Comment by AThomsen** [comment]
Just want to let you know that I'm still working on this.
It runs very well and I'm currently working on switching the previewer dialog to use the new implementation as well. The plan is actually to have it use MediaBackend to get rid of duplicate code.

The code is here if you want to check it out: https://github.com/AThomsen/OpenKJ/tree/feature/cdg-on-demand-reader

**Comment by coyote1357** [comment]
I went ahead and merged your changes, though I think you had one more fix pending that you were working on.  Just seemed better than going back in and fixing conflicts for each of the things I was working on since so many files were involved in the PR.

Very nice work all around, really.  I seriously appreciate the effort you're putting into this.  You're the first skilled dev that's submitted code since I started this whole thing.

Oh, and I love the gst pipeline graph output item you added to the testing menu.  Very handy.

I'd actually like to pick your brain about some stuff if you don't mind.  If you have a preferred messaging platform and wouldn't mind, shoot me the details in an email to support@openkj.org

**Comment by AThomsen** [comment]
Glad you like it :-)   Your approach reminds me very much of my own first projects.
Not doing much coding at work any more so it's fun to have some open source projects to work on.

I've discovered a few bugs in the PR which I will fix this weekend and provide as single PRs.

**Comment by coyote1357** [comment]
Something is wrong on Windows, at least on my 2 test machines.  Pipeline can't start, throws errors in the input audioconvert element.

Btw, modified the gst graph output to work on windows if graphviz is installed and to put the images in the current user's default pictures directory.

**Comment by coyote1357** [comment]
Figured it out.  Windows needs an audioresample element after the aConvInput element.  No idea why this is needed on Windows but not on Linux.  I guess PulseAudio is more forgiving of different sample rates? (wild ass guess lol)
