### ISSUE TITLE
Get Request Model/Routine

### ISSUE THREAD

**Issue by ergodaveh** [OpenKJ/OpenKJ#3]
Thanks for providing the OpenKJ

Attempting to understand the Requests Table Model and noticed this service is supported with 'php' files such as 'getRequests.php' and others.   I've typically done things in html or asp/x 'ish , could you share those php files?  

Cheers,

**Comment by coyote1357** [comment]
Apologies for that, I still haven't "universalized" the server side php code for that bit yet.  I kinda threw it together as I went and it's a bit of a mess.  I'll try to get it into a state that's usable by other people and get it up on git soon.  Hope you're finding the rest of the program usable.

**Comment by coyote1357** [comment]
There's a public requests server up now at http://songbook.openkj.org if you want to play with it.  I should have documentation of the JSON APIs available soon.  It's all been reworked as part of setting up the hosted service.  There are more details on the hosted requests server in the readme or on the OpenKJ [facebook page](https://facebook.com/OpenKJ).

**Comment by ergodaveh** [comment]
Awesome  Thanks for providing.  Looking forward to the doc and taking it for a test drive.

**Comment by coyote1357** [comment]
FYI, there was a bug that was preventing updating the remote database.  Boneheaded move by me, accidentally left a hardcoded testing API key in the update code (facepalm).  Everyone was updating my test account's songs db table instead of their own.  I didn't notice it until I tried to update my real account for my show last night.  New builds should be up shortly.  So, if you tried it out and it didn't work, that's why.
