### ISSUE TITLE
Karaoke CD playback

### ISSUE THREAD

**Issue by djjimi** [OpenKJ/OpenKJ#30]
Just simple CDG Disk playback ability - would also be nice if it had the capability to rip too, as there is literally only ONE other piece of software for Mac that will do this.  I don't even want the software to try to index the tracks.

**Comment by vipermetcaff** [comment]
have you tryed audacity and all you need to do is get the lame encorderhttp://www.audacityteam.org/download/mac/

**Comment by djjimi** [comment]
?? I use Audacity on a daily basis... and have for the last 10+ years, and I have no idea what you're talking about.  How is the lame encoder enabling the reading and ripping .bin files off of a disk?

**Comment by coyote1357** [comment]
In order to add CD+G disc playback, I'd have to come up with a cross platform way to directly access the raw data in the subchannels that the graphics are encoded in, or write and maintain 3 separate implementations, and make pretty major overhauls to the CDG decoding library I wrote that handles the graphics in OpenKJ.  As much as I would love to add that feature, I don't foresee being able to do so any time soon.

As far as ripping goes, I'll look into seeing if there's an existing cross-platform tool that I could wrap a UI around.

**Comment by djjimi** [comment]
Thanks Coyote.  I know that it's available in KJams (both reading and ripping actually), but alas, I am unable to use it any longer as my library has exceeded what their database can handle.

**Comment by frogonwheels** [comment]
I recently did some ripping with cdgtools, which works from a  cdgrao rip of a CD.  It was most painful, as there doesn't seem to be any track names embedded, and so you are relying on CDDB servers which don't seem to cater for CD+G cds. I ended up using vim to mangle copy+paste from the website to get the names...
