### ISSUE TITLE
Request about background music

### ISSUE THREAD

**Issue by Karaokay** [OpenKJ/OpenKJ#40]
I really like open KJ, but the background music side of things could benefit from a few additions IMO.
The pub I work will occsionally have a night where there are few singers, so background music becomes more important.
i like being able to load playlists i've created in other software, but i usually mix and match them,,eg.
(if you've ever used virtual dj you'll know what i'm aiming at)
I will view a playlist and select a few songs from it to add to a currently playing list, then if necessary i can save that new playlist to play another time.
also after a song has played it auto removes from the currently playing list.
the playlist screen could be split in half vertically to allow this, with the top half showing the currently playing and the bottom half viewing the loaded playlist.
does that make sense?
also the ability to fade from one track into another without silence would be really good.

thanks

**Comment by coyote1357** [comment]
Hello, and thanks for the feedback/suggestions. :) 

Yeah, the break music portion of OpenKJ is still very basic at this point since most of my development effort has been going toward the karaoke specific side of things, as that's very much the primary focus of the software. It's basically just a convenience feature to avoid having to manually fade break music in and out between karaoke singers.  I do plan on flushing it out more, but it will probably always remain somewhat simple, particularly compared to something like Virtual DJ (which I've never used, but just googled and looked at and it looks perfect for non-karaoke DJing).

True crossfading w/o silence has actually been requested by multiple people, is doable, and is on giant list o' things to implement, but it will require a pretty major re-write of the audio backend, so it's probably gonna be a bit before I can get to it.

**Comment by backstagekaraoke** [comment]
This is being addressed already in a current revamp of the fader, silence detection functions.
