### ISSUE TITLE
Documentation of Settings?

### ISSUE THREAD

**Issue by henry74** [OpenKJ/OpenKJ#5]
@coyote1357 Thanks for putting this out there as open source.  I've been looking for a decent player for CDG files.  I'm trying to get my head wrapped around some of the features which aren't documented.  

Can you explain how I can take advantage of the Settings->Network->Use request server?  
How do I take advantage of incoming requests?
What are regulars?

Any documentation you can point me to would be super helpful :-)

Thanks.

**Comment by coyote1357** [comment]
Regulars are singers who regularly show up at a karaoke venue.  It's a convenience feature that tracks and saves their song queues so that they can be loaded back in whenever they visit, as most singers tend to sing the same songs every week.  It's indicated by the "heart" column on the rotation list.  To save someone as a regular, you just click the heart on their queue entry.  To load them back in to a new rotation, you click the heart button below the rotation and then click the plus beside their name in the dialog that pops up.

Incoming requests requires a web server be setup hosting some php code that I haven't published yet.  I will eventually get it up on github, but it needs to be modified for general use outside of my karaoke shows.  It's on my list o' things to do, but bugfixes and other changes are higher up, and between being a full time enterprise Linux admin and a weekend karaoke DJ, I only get so much free time to work on it.

Documentation is also on my list, heh, but you know how much developers LOVE writing documentation.  ;) That bad excuse aside, I'm planning some UI changes that need to happen before documenting the software.

**Comment by coyote1357** [comment]
Documentation of the audio/video/network settings in the settings dialog is now up at https://openkj.org, and there is also a getting started guide that covers the basics of using it for managing the database, rotation, and regulars.  More documentation is in the works as well.

Also, while the JSON API documentation isn't done yet for people who want to roll their own, there is a (currently free) request server service setup at https://songbook.openkj.org   It allows you to point your singers to a website for search and submission of songs, which will pop up in OpenKJ within 10 seconds of when they submit them (assuming you have good network connectivity).

Sorry this all took so long to get around to.
