### ISSUE TITLE
OpenKJ  Recording Feature

### ISSUE THREAD

**Issue by ergodaveh** [OpenKJ/OpenKJ#6]
Any guidance on using the recording feature?

**Comment by coyote1357** [comment]
Generally, it's meant to be used with a mixer with a USB audio interface that shows up as an input on the computer.  I have only tested it with a Mackie mixer, because that's what I'm currently using.

**Comment by ergodaveh** [comment]
Thanks for the reply.   I have attempted to use the feature using a USB Yeti Microphone as a device..    I have setup these options
"Recording" <<selected
"Captive Device" << Yeti Device was found
"Audio codec" 'audio/pcm'
"Container 'audio/x-raw'
"Output Directory"  'C:/Users/-/Music/Karaoke Recordings'

are there any other setting/option/activation methods?
-Dave

**Comment by coyote1357** [comment]
No, if it's working it should just start automatically generating recordings of the karaoke songs starting when the song starts, and ending when it ends.  Note that I haven't tested that particular feature at all on Windows, so there is a good chance it won't work and I'll need to take a look.

**Comment by ergodaveh** [comment]
With the testing of a Windows build.  I have noticed within KhAudioRecorder

 This string contained a reserved character ":" within the formatted date-time
I have simply removed it...
 startDateTime = QDateTime::currentDateTime().toString("yyyy-MM-dd hh mm");

Then i changed this trap
 if (settings->recordingContainer() == "audio/x-raw")
    
        outputFilePath = outputDir + QDir::separator() + filename + ".raw";

    else
   
        outputFilePath = outputDir + QDir::separator() + filename + ".wav";

and later described the setOutputLocation to use a prefix "file:///" as see below

audioRecorder->setOutputLocation(QUrl("file:///"+ outputFilePath)); 

and the process runs on a Windows local.

I am wanting to explore a codec for m4a format.  How would I add another 'Audio Backend' as such  DirectShow or  WMF

**Comment by coyote1357** [comment]
I'll look at taking that out for better x-platform compat, thanks for figuring out what was going on.

As far as the codecs go, it's just using the QAudioRecorder class, which "should" be able to use any codec on the system.  I'm only using gstreamer for the playback because I needed features that the QtMultimedia classes don't have (pitch shifting, downmixing, etc).

In settings, it's just pulling a list of supported codecs and containers specific to the system it's running on.  This is from the settings dialog code, where you set the codec and container.

    QAudioRecorder audioRecorder;
    QStringList inputs = audioRecorder.audioInputs();
    QStringList codecs = audioRecorder.supportedAudioCodecs();
    QStringList containers = audioRecorder.supportedContainers();
    ui->groupBoxRecording->setChecked(settings->recordingEnabled());
    ui->comboBoxDevice->addItems(inputs);
    ui->comboBoxCodec->addItems(codecs);
    ui->comboBoxContainer->addItems(containers);

**Comment by coyote1357** [comment]
Also, as an FYI, automated windows builds for each git commit are coming soon.  I'm actually working on that right now.  I've already got it to where one script running on a gcloud compute Windows Server VM clones git, compiles everything, generates an installer, and puts it on my webserver.  I'm working on making it triggerable via github webhooks now.  And the windows installer is going to be a lot better as well, I'm abandoning the Qt installer creation tool.  The guys over at Advanced Installer were kind enough to give me a free professional license to use with the project.  No more error every time if you already have the msvc redistributables on the system.

**Comment by coyote1357** [comment]
Automated Windows builds are now up and working but aren't linked off the main site or github page yet.  There's a build up with the bad special character removed from the autogenerated directory names.  https://www.openkj.org/downloads/Windows64/

**Comment by coyote1357** [comment]
I finally ran it on Windows and I see what you're saying about the codecs.  Last time I tested it was on a Win7 machine, and I don't remember being restricted to just raw or wav.  Something must have changed in either Qt since then or in the way the Windows audio subsystem works.   If I can't work out how to get QAudioRecorder to work the way it used to on Windows, I'll see how hard it would be to switch to gstreamer for recording as well.

**Comment by coyote1357** [comment]
Switched recording to use gstreamer as its backend instead of QAudioRecorder to get around the lack of encoding codecs on Windows in QtMultimedia.  Validated that it's working on a Windows 10 system.  Only caveat is that you can't pick your output device from inside OpenKJ on Windows.  But it should use whatever you have set as your default input device via the Windows audio settings when the program launches.  Currently supported output codecs are PCM/WAV, Ogg Vorbis, and mp3.  I actually tried adding AAC/m4a, but couldn't figure out how to build a gstreamer pipeline that actually output good files even though it theoretically supports it.  The most recent Windows build on the OpenKJ.org website has the new recording stuff in it.  If you're compiling from source, you'll need to make sure you have gstreamer's audio encoding stuff installed (It's not as part of the default install).

**Comment by coyote1357** [comment]
Oh, please let me know if it works.  Don't want to close the issue until someone other than myself gets a good test result. :)

**Comment by coyote1357** [comment]
Verified working by a local KJ, so I'm closing the ticket. If it doesn't work from you, we can reopen the ticket.
