### ISSUE TITLE
Ticker

### ISSUE THREAD

**Issue by vipermetcaff** [OpenKJ/OpenKJ#80]
add the atrist and song name  to the ticker so the next Person knows what song there singing

**Comment by PalasX** [comment]
Instead of this, consider a text replacement system. Allow text box entries for each part of the ticker that can be either static text, or a specific string that will be swapped with relevant info.

E.g. if you have a text box for the "For each singer" portion of the text scroll, allow '&&SinerName', '&&Artist', '&&SongName', etc to be replaced with the relevant info. This info can be updated in the same loop you use to current grab the singers name.

**Comment by jackflack69** [comment]
I saw this and I wanted to say I think PalasX has the right idea. It would be nice to have auto-case too. So something like Singer Name could be $singer for case sensitive and $SINGER would be ALL CAPS no matter what case was typed.

**Comment by coyote1357** [comment]
As of 1.3.78, the following variable substitutions are available

%curSinger = Current singer name
%curSong = Current song (aritst - title)
%curArtist = Current artist
%curTitle = Current title
%nextSinger = Next singer name

No auto-case yet.  Will expand further later.

**Comment by apiontek** [comment]
It would be helpful to be able to show the next song as well - my preferred ticker would be:

%curSinger: %curSong | %nextSinger: %nextSong | ...

And actually, it'd be ideal if the ticker could support multiple "%nextSinger: %nextSong" items to show the next 2, 3, 4, etc singers. I'm not sure what the best way to do this would be, but maybe inserting some sort of "%upcoming" block, which would show the upcoming queue data, and could have its own settings for how many queued items to show and what format to show for each queued item.

So instead one's custom substitutions could be

%curSinger: %curSong | %upcoming

And then a separate settings area for the %upcoming format that I'd set to

%queueSinger: %queueSong

Items to show: [n] (number field)

and the display would show the next [n] items in the format specified. Does that make any sense?
