### ISSUE TITLE
A overview of the database

### ISSUE THREAD

**Issue by Babham** [OpenKJ/OpenKJ#87]
Thanks for the magnificent work of yours on OpenKJ!

I would love to be able to see the whole database as it is in OpenKJ but in the iPhone app or on songbook.openkj.org

Would that be doable or do you have any other way of displaying/inspiring songs to the audience?

For me just seeing different categories and songs gives me inspiration to choose a song or so... 
Or do any of you guys have a good work around?

All the best, and keep up the good work : )

And by the way, the current build works great on my iMac!

**Comment by vipermetcaff** [comment]
he has a standalone verson  you can setup on your own server
https://github.com/OpenKJ/StandaloneRequestServer
ive been useing it an it works great

**Comment by coyote1357** [comment]
I'm not sure what you mean by "as it is in OpenKJ"... When you push your DB to the server it's based on your entire library.  The only thing it does is strip SongIDs and it tries to deduplicate down to unique artist/title entries.  Since there are no categories in the software, I'm not sure what you're referring to...

Glad it's working well for you on Mac! :)

**Comment by frogonwheels** [comment]
The other way of approaching this would be to do something like have a rest api on the actual application so that you could interact with the main application from a web/device.
