### ISSUE TITLE
Break Music default level on start. Also list of Windows Build issues.

### ISSUE THREAD

**Issue by jackflack69** [OpenKJ/OpenKJ#88]
Updating post based on the conversation we had. Windows (x64) ver. 1.3.59 unstable.

* Default path for song purchases not a valid path. C:/Users/localadmin/Music\OpenKJ_Downloads\
it should be C:\ %HomePath%\Music\OpenKJ_Downloads\ (no space after C:\ )

* In the Main Karaoke window the Rotation and Singers sub windows cannot be adjusted Up, Down, and Left, Right. The far right tab such as the delete X in Rotation and Singers cannot be adjusted to shrink the tab. Adjustments create one large delete X that gets clicked on accident more than once and a while.

* In the Break Music Tab the same issue exists. In Database the song time cannot be adjusted from right to left. In Playlist the delete X cannot be adjusted right to left.

* Settings, Check for update on startup selected with Development. Application does not notify you of new unstable version available for download

Hey Issac, its California.

Been playing with Windows (x64) build 1.3.47 for fun and thought I would mess with the unstable builds so you could get some feedback on the Windows side.

If you leave the OpenKJ application without Break Music playing, then on restart, say after a crash, then OpenKJ leaves the volume level at 0 when it starts the break music with Settings/Other: Start break music checked. I was thinking having it remember last setting played at, but it would be 0 still in that situation

Maybe have a default level of 0-100 number box that can be preset. It will then default to that level if the check box for start break music on program launch is selected. So no matter the last thing done in OpenKJ, it will always set it to the default level on startup.

Other than that, This build is pretty damn stable.

Hope this was helpful. Hope to be up next weekend too.

-California

**Comment by jackflack69** [comment]
updated.

**Comment by coyote1357** [comment]
Fortunately Windows these days supports both DOS style and POSIX standard style slashes in paths, so while the first one isn't pretty, it should actually work.

I *think* the sizing issues should be fixed in current versions.  

The development version updates not alerting is server side, there's a problem there I need to fix.  It's not getting updated by the automated build system like it's supposed to.

Startup volume is definitely something that either needs to ignore fade out state on program shutdown or that can be configured to a static level.  It's on the ol' list.
