### ISSUE TITLE
New Feature Request: List View for singer rotation.

### ISSUE THREAD

**Issue by crbunch** [OpenKJ/OpenKJ#89]
Once again this project is wonderful and all would like to do is help if I can. 

New Feature request:
I am the type of person that comes from a pen and paper karaoke gig hauling cases of karaoke discs with me. I am use to when someone comes up to sign up for a song I go down the list even though they are regulars. I was wondering if there is a way to change the view or create a list view so I can move people up and down the list verses having a list of singers and their songs. I guess I am just stupid and I can't wrap my head around the concept.

**Comment by frogonwheels** [comment]
I think you might be wanting what I was after  - which is having an overall queue of singers and their songs, (which you could also maintain the order of),  rather than having the queue per singer.
This would work very well for a 'party' scenario where you have the same couple of people signing up a song and you just want them to take their turn in the overall queue of songs - rather than them singing all the songs they have queued up.

**Comment by frogonwheels** [comment]
@crbunch - I have now delved into the code, and understand how the database is organised a _bit_more.  Some of my confusion was because whenever I clicked on an item it would try to change the song being played, and much of that was the difference in behaviour of a QT app under different environments (which is generally a good thing). I made some changes to fix that up - hopefully they will be accepted, but I'm expecting some conversations before they are.

I think once you get used to the idea of a rotation of singers, each with their own song-list, that it won't be so bad.  I do know that there would be a fair bit of reorganisation to have it work differently. I guess you could have a separate table to handle a 'song queue mode'.. but it would mean a bit of abstracting the concept of get next song, and effectively switching between two entirely different modes.

**Comment by apiontek** [comment]
Personally, I can wrap my head around "singer rotation, each singer with their own list," but I'd prefer have some flexibility.

What I'd like to see:

- Sticking with the current way of doing it, it would _at least_ be nice to have an indicator in the singer rotation list of what the rotation _is:_ Who's up next? Who's after that? As it is, I can't tell without looking at the ticker. This info should be in the DJ interface.

- I would _also_ like to be able to toggle the Song Queue from "selected singer's queue" into a view that just shows the entire song queue, with a first column showing singer name.

Those two modifications don't need to include manually managing the full song queue, though that would be a nice addition.
